version: '3.3'
networks:
  localnet:
services:
  sftp: # docker run -p 0.0.0.0:21021:22 -dv /tmp:/home/sftp-user/uploads atmoz/sftp sftp-usern:sftp-password
    image: atmoz/sftp # sed -n '/\[0\.0\.0\.0]:21021/!p' ~/.ssh/known_hosts > ~/.ssh/known_hosts
    command: "sftp-user:sftp-password" # ${sftpConfig.user}:${sftpConfig.password}
    volumes: ['./target:/home/sftp-user/uploads'] # ${sftpConfig.baseDir}
    ports: ['21021:22']
    networks: [localnet]
