name: 'Spring Batch for cloud 1: plain old Spring Batch'
on:
  workflow_dispatch:
    inputs:
      trigger:
        description: Type m to triggre manual jobs
        required: false
        default: ''
  push:
jobs:
  step-1-plain-old-batch:
    name: java-${{ matrix.java }} step-1-plain-old-batch
    if: github.event.inputs.trigger == ''
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [ 8, 11, 17, 18 ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - uses: actions/cache@v3
        id: ci
        with:
          path: |
            ~/.npm
            ~/.node
            ~/.local
            ~/.gradle
            ~/.docker
            ~/.m2/repository
            !~/.m2/repository/com/gituhb/daggerok
          key: ${{ runner.os }}-${{ hashFiles('**/*.gradle', '**/pom.xml') }}
      - uses: actions/setup-node@v2
      - run: rm -rf ~/.m2/repository/com/github/daggerok
      - run: cd $GITHUB_WORKSPACE/batch-to-cloud/step-1-plain-old-batch ; ./mvnw clean install
      - run: cd $GITHUB_WORKSPACE/batch-to-cloud/step-1-plain-old-batch ; ./mvnw spring-boot:start -f app
      - run: cd $GITHUB_WORKSPACE/batch-to-cloud/step-1-plain-old-batch ; ./mvnw spring-boot:start -f user-service
      - run: cd $GITHUB_WORKSPACE/batch-to-cloud/step-1-plain-old-batch ; ./mvnw spring-boot:start -f payment-service
      - run: sudo apt install -yqq httpie
      - run: http --ignore-stdin get  :8080/api
      - run: http --ignore-stdin post :8080/api/launch-payments-report
      - run: cd $GITHUB_WORKSPACE/batch-to-cloud/step-1-plain-old-batch ; ./mvnw spring-boot:stop -f app
      - run: cd $GITHUB_WORKSPACE/batch-to-cloud/step-1-plain-old-batch ; ./mvnw spring-boot:stop -f user-service
      - run: cd $GITHUB_WORKSPACE/batch-to-cloud/step-1-plain-old-batch ; ./mvnw spring-boot:stop -f payment-service
      - run: cat $GITHUB_WORKSPACE/batch-to-cloud/step-1-plain-old-batch/app/target/payments-report.csv
