name: Spring Batch job scheduling
on:
  workflow_dispatch:
    inputs:
      trigger:
        description: Type m to triggre manual jobs
        required: false
        default: ''
  #pull_request: [ master ]
  push:
jobs:
  spring-batch-job-scheduling:
    name: java-${{ matrix.java }} spring-batch-job-scheduling
    if: github.event.inputs.trigger == ''
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        java: [ 8, 11, 17, 18 ]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - uses: actions/cache@v3
      id: ci
      with:
        path: |
          ~/.npm
          ~/.node
          ~/.local
          ~/.gradle
          ~/.docker
          ~/.m2/repository
          !~/.m2/repository/com/gituhb/daggerok
        key: ${{ runner.os }}-${{ hashFiles('**/*.gradle', '**/pom.xml') }}
    - uses: actions/setup-node@v2
    - run: cd $GITHUB_WORKSPACE/spring-batch-job-scheduling ; ./mvnw clean install -q
    - run: |
        cd $GITHUB_WORKSPACE/spring-batch-job-scheduling ; ./mvnw spring-boot:start
        sleep 10s
        cd $GITHUB_WORKSPACE/spring-batch-job-scheduling ; ./mvnw spring-boot:stop
        sleep 25s
